# Generated by Django 5.0.6 on 2024-06-13 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("connections", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connected_users",
                to="profiles.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connections",
                to="profiles.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="connectionrequest",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connection_requests_sent",
                to="profiles.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="connectionrequest",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connection_requests_received",
                to="profiles.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="recommended_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations_given",
                to="profiles.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="recommended_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations_received",
                to="profiles.userprofile",
            ),
        ),
    ]
