# Generated by Django 5.0.6 on 2024-06-13 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activity", "0003_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("event_date", models.DateField()),
                ("capacity", models.PositiveIntegerField()),
                ("category", models.CharField(max_length=50)),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="profiles.userprofile"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="events_categoories", to="activity.category"
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_events",
                        to="profiles.userprofile",
                    ),
                ),
            ],
        ),
    ]
