# Generated by Django 5.0.6 on 2024-06-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="comments",
            field=models.ManyToManyField(
                blank=True, related_name="course_comments", to="posts.comment"
            ),
        ),
    ]
