# Generated by Django 5.0.6 on 2024-06-13 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activity", "0002_initial"),
        ("messaging", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="members",
            field=models.ManyToManyField(
                db_index=True, related_name="chatrooms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="attachments",
            field=models.ManyToManyField(
                blank=True,
                db_index=True,
                related_name="message_attachments",
                to="activity.attachment",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="messaging.chatroom"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="messaging.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="reactions",
            field=models.ManyToManyField(
                db_index=True, related_name="message_reactions", to="activity.reaction"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="shares",
            field=models.ManyToManyField(
                blank=True, related_name="message_shares", to="activity.share"
            ),
        ),
    ]
