# Generated by Django 5.0.6 on 2024-06-13 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="followers",
            field=models.ManyToManyField(
                related_name="followed_companies", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="members",
            field=models.ManyToManyField(
                related_name="member_companies", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="companyupdate",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_updates",
                to="companies.company",
            ),
        ),
    ]
