# Generated by Django 5.0.6 on 2024-06-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("issuing_organization", models.CharField(max_length=255)),
                ("issue_date", models.DateField()),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("credential_id", models.CharField(blank=True, max_length=255)),
                ("credential_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "certificate_image",
                    models.ImageField(blank=True, upload_to="certificates/"),
                ),
                ("verification_status", models.BooleanField(default=False)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="certifications_categories", to="activity.category"
                    ),
                ),
            ],
        ),
    ]
