# Generated by Django 5.0.6 on 2024-06-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("certifications", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="related_courses",
            field=models.ManyToManyField(
                blank=True, related_name="courses_certifications", to="courses.course"
            ),
        ),
    ]
