# Generated by Django 5.0.6 on 2024-06-13 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("certifications", "0001_initial"),
        ("courses", "0001_initial"),
        ("jobs", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="related_courses",
            field=models.ManyToManyField(
                blank=True, related_name="courses_certifications", to="courses.course"
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="related_jobs",
            field=models.ManyToManyField(
                blank=True, related_name="job_certifications", to="jobs.joblisting"
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_certifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
