# Generated by Django 5.0.6 on 2024-06-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("certifications", "0002_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="related_jobs",
            field=models.ManyToManyField(
                blank=True, related_name="job_certifications", to="jobs.joblisting"
            ),
        ),
    ]
