# Generated by Django 5.0.6 on 2024-06-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_alter_notification_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationtype",
            name="type_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
